# WRC2020_View

Visualisers applied directly to `WRCEvent` data object.

In [48]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [49]:
from WRC_2020 import WRCEvent

In [50]:
!rm wrc2020swetest1.db
event = WRCEvent(dbname='wrc2020swetest1.db')

event.rallyslurper()

upserting into [('rally', ['sdbRallyId']), ('eligibilities', ['sdbRallyId', 'category']), ('groups', ['sdbRallyId', 'groupId'])]
upserting into [('itinerary', ['itineraryId']), ('legs', ['itineraryLegId']), ('sections', ['itinerarySectionId']), ('controls', ['controlId']), ('stages', ['stageId']), ('richstages', ['stageId'])]
upserting into [('startList', ['startListId']), ('startListItems', ['startListItemId'])]
upserting into [('penalties', 'penaltyId')]
upserting into [('retirements', 'retirementId')]
upserting into ('stagewinners', ['stageId', 'entryId'])
upserting into [('cars', ['entryId', 'eventId']), ('classes', ['entryId'])]
SS2 1566
upserting into overall
upserting into stagetimes
upserting into splitPoints
upserting into entrySplitPointTimes
upserting into splitPointTimes
SS3 1563
upserting into overall
upserting into stagetimes
upserting into splitPoints
upserting into entrySplitPointTimes
upserting into splitPointTimes
SS4 1562
upserting into overall
upserting into stagetimes
upserting into splitPoints
upserting into entrySplitPointTimes
upserting into splitPointTimes
SS8 1571
upserting into overall
upserting into stagetimes
upserting into splitPoints
upserting into entrySplitPointTimes
upserting into splitPointTimes
SS5 1564
upserting into overall
upserting into stagetimes
upserting into splitPoints
upserting into entrySplitPointTimes
upserting into splitPointTimes
SS6 1565
upserting into overall
upserting into stagetimes
upserting into splitPoints
upserting into entrySplitPointTimes
upserting into splitPointTimes
SS7 1567
upserting into overall
upserting into stagetimes
upserting into splitPoints
upserting into entrySplitPointTimes
upserting into splitPointTimes
SS16 1568
upserting into overall
upserting into stagetimes
upserting into splitPoints
upserting into entrySplitPointTimes
upserting into splitPointTimes
SS18 1572
upserting into overall
upserting into stagetimes
upserting into splitPoints
upserting into entrySplitPointTimes
upserting into splitPointTimes

In [67]:
event.getSplitTimes()[1][1566]

,entryId,startDateTime,startDateTimeLocal,stageTimeDurationMs,stageTimeDuration,stageId
0,20771,2020-02-14T07:42:00,2020-02-14T08:42:00+01:00,588300,00:09:48.3000000,1566
1,20772,2020-02-14T07:45:00,2020-02-14T08:45:00+01:00,586800,00:09:46.8000000,1566
2,20773,2020-02-14T07:48:00,2020-02-14T08:48:00+01:00,583900,00:09:43.9000000,1566
3,20774,2020-02-14T07:51:00,2020-02-14T08:51:00+01:00,590200,00:09:50.2000000,1566
4,20775,2020-02-14T07:54:00,2020-02-14T08:54:00+01:00,585900,00:09:45.9000000,1566
5,20777,2020-02-14T07:57:00,2020-02-14T08:57:00+01:00,592100,00:09:52.1000000,1566
6,20776,2020-02-14T08:00:00,2020-02-14T09:00:00+01:00,597000,00:09:57,1566
7,20778,2020-02-14T08:03:00,2020-02-14T09:03:00+01:00,585000,00:09:45,1566
8,20779,2020-02-14T08:06:00,2020-02-14T09:06:00+01:00,595800,00:09:55.8000000,1566
9,20780,2020-02-14T08:09:00,2020-02-14T09:09:00+01:00,593300,00:09:53.3000000,1566
10,20782,2020-02-14T08:12:00,2020-02-14T09:12:00+01:00,621200,00:10:21.2000000,1566
11,20783,2020-02-14T08:15:00,2020-02-14T09:15:00+01:00,635500,00:10:35.5000000,1566
12,20784,2020-02-14T08:18:00,2020-02-14T09:18:00+01:00,623700,00:10:23.7000000,1566
13,20785,2020-02-14T08:21:00,2020-02-14T09:21:00+01:00,651800,00:10:51.8000000,1566
14,20786,2020-02-14T08:24:00,2020-02-14T09:24:00+01:00,614500,00:10:14.5000000,1566
15,20787,2020-02-14T08:27:00,2020-02-14T09:27:00+01:00,624900,00:10:24.9000000,1566
16,20791,2020-02-14T08:28:00,2020-02-14T09:28:00+01:00,621300,00:10:21.3000000,1566
17,20792,2020-02-14T08:29:00,2020-02-14T09:29:00+01:00,625300,00:10:25.3000000,1566
18,20793,2020-02-14T08:30:00,2020-02-14T09:30:00+01:00,621900,00:10:21.9000000,1566
19,20794,2020-02-14T08:31:00,2020-02-14T09:31:00+01:00,628700,00:10:28.7000000,1566
20,20795,2020-02-14T08:32:00,2020-02-14T09:32:00+01:00,632600,00:10:32.6000000,1566
21,20796,2020-02-14T08:33:00,2020-02-14T09:33:00+01:00,664800,00:11:04.8000000,1566
22,20797,2020-02-14T08:34:00,2020-02-14T09:34:00+01:00,657300,00:10:57.3000000,1566
23,20799,2020-02-14T08:35:00,2020-02-14T09:35:00+01:00,655200,00:10:55.2000000,1566
24,20800,2020-02-14T08:36:00,2020-02-14T09:36:00+01:00,668300,00:11:08.3000000,1566
25,20801,2020-02-14T08:37:00,2020-02-14T09:37:00+01:00,725200,00:12:05.2000000,1566
26,20804,2020-02-14T08:39:00,2020-02-14T09:39:00+01:00,669300,00:11:09.3000000,1566
27,20805,2020-02-14T08:40:00,2020-02-14T09:40:00+01:00,679500,00:11:19.5000000,1566
28,20806,2020-02-14T08:41:00,2020-02-14T09:41:00+01:00,690800,00:11:30.8000000,1566
29,20807,2020-02-14T08:42:00,2020-02-14T09:42:00+01:00,694400,00:11:34.4000000,1566
30,20808,2020-02-14T08:43:00,2020-02-14T09:43:00+01:00,697300,00:11:37.3000000,1566
31,20809,2020-02-14T08:44:00,2020-02-14T09:44:00+01:00,712800,00:11:52.8000000,1566
32,20810,2020-02-14T08:45:00,2020-02-14T09:45:00+01:00,889700,00:14:49.7000000,1566
33,20811,2020-02-14T08:46:00,2020-02-14T09:46:00+01:00,708300,00:11:48.3000000,1566
34,20812,2020-02-14T08:47:00,2020-02-14T09:47:00+01:00,680300,00:11:20.3000000,1566
35,20813,2020-02-14T08:48:00,2020-02-14T09:48:00+01:00,704200,00:11:44.2000000,1566
36,20814,2020-02-14T08:49:00,2020-02-14T09:49:00+01:00,705800,00:11:45.8000000,1566
37,20815,2020-02-14T08:50:00,2020-02-14T09:50:00+01:00,716900,00:11:56.9000000,1566
38,20816,2020-02-14T08:51:00,2020-02-14T09:51:00+01:00,744600,00:12:24.6000000,1566
39,20817,2020-02-14T08:52:00,2020-02-14T09:52:00+01:00,756300,00:12:36.3000000,1566
40,20818,2020-02-14T08:53:00,2020-02-14T09:53:00+01:00,753700,00:12:33.7000000,1566
41,20819,2020-02-14T08:54:00,2020-02-14T09:54:00+01:00,774800,00:12:54.8000000,1566
42,20820,2020-02-14T08:58:00,2020-02-14T09:58:00+01:00,676000,00:11:16,1566
43,20821,2020-02-14T08:59:00,2020-02-14T09:59:00+01:00,682500,00:11:22.5000000,1566
44,20822,2020-02-14T09:00:00,2020-02-14T10:00:00+01:00,670500,00:11:10.5000000,1566
45,20823,2020-02-14T09:01:00,2020-02-14T10:01:00+01:00,725100,00:12:05.1000000,1566

In [75]:
# TO DO  - do we have startlists for each stage?
event.getStartlist()

upserting into [('startList', ['startListId']), ('startListItems', ['startListItemId'])]

(   startListId  eventId publishedStatus    name
 0          460      125       Published  Friday,
     startListItemId  startListId  entryId        startDateTime  \
 0             21459          460    20801  2020-02-14T06:57:00
 1             21460          460    20804  2020-02-14T06:58:00
 2             21461          460    20805  2020-02-14T06:59:00
 3             21462          460    20806  2020-02-14T07:00:00
 4             21463          460    20807  2020-02-14T07:01:00
 5             21464          460    20808  2020-02-14T07:02:00
 6             21465          460    20809  2020-02-14T07:03:00
 7             21466          460    20810  2020-02-14T07:04:00
 8             21467          460    20811  2020-02-14T07:05:00
 9             21468          460    20800  2020-02-14T06:56:00
 10            21469          460    20812  2020-02-14T07:06:00
 11            21470          460    20814  2020-02-14T07:08:00
 12            21471          460    20815  2020-02-14T07:09:00
 13            21472          460    20816  2020-02-14T07:10:00
 14            21473          460    20817  2020-02-14T07:11:00
 15            21474          460    20818  2020-02-14T07:12:00
 16            21475          460    20819  2020-02-14T07:13:00
 17            21476          460    20820  2020-02-14T07:17:00
 18            21477          460    20821  2020-02-14T07:18:00
 19            21478          460    20822  2020-02-14T07:19:00
 20            21479          460    20813  2020-02-14T07:07:00
 21            21480          460    20823  2020-02-14T07:20:00
 22            21481          460    20799  2020-02-14T06:55:00
 23            21482          460    20796  2020-02-14T06:53:00
 24            21483          460    20772  2020-02-14T06:05:00
 25            21484          460    20773  2020-02-14T06:08:00
 26            21485          460    20774  2020-02-14T06:11:00
 27            21486          460    20775  2020-02-14T06:14:00
 28            21487          460    20777  2020-02-14T06:17:00
 29            21488          460    20776  2020-02-14T06:20:00
 30            21489          460    20778  2020-02-14T06:23:00
 31            21490          460    20779  2020-02-14T06:26:00
 32            21491          460    20780  2020-02-14T06:29:00
 33            21492          460    20797  2020-02-14T06:54:00
 34            21493          460    20782  2020-02-14T06:32:00
 35            21494          460    20784  2020-02-14T06:38:00
 36            21495          460    20785  2020-02-14T06:41:00
 37            21496          460    20786  2020-02-14T06:44:00
 38            21497          460    20787  2020-02-14T06:47:00
 39            21498          460    20791  2020-02-14T06:48:00
 40            21499          460    20792  2020-02-14T06:49:00
 41            21500          460    20793  2020-02-14T06:50:00
 42            21501          460    20794  2020-02-14T06:51:00
 43            21502          460    20795  2020-02-14T06:52:00
 44            21503          460    20783  2020-02-14T06:35:00
 45            21504          460    20771  2020-02-14T06:02:00

            startDateTimeLocal  order
 0   2020-02-14T07:57:00+01:00     26
 1   2020-02-14T07:58:00+01:00     27
 2   2020-02-14T07:59:00+01:00     28
 3   2020-02-14T08:00:00+01:00     29
 4   2020-02-14T08:01:00+01:00     30
 5   2020-02-14T08:02:00+01:00     31
 6   2020-02-14T08:03:00+01:00     32
 7   2020-02-14T08:04:00+01:00     33
 8   2020-02-14T08:05:00+01:00     34
 9   2020-02-14T07:56:00+01:00     25
 10  2020-02-14T08:06:00+01:00     35
 11  2020-02-14T08:08:00+01:00     37
 12  2020-02-14T08:09:00+01:00     38
 13  2020-02-14T08:10:00+01:00     39
 14  2020-02-14T08:11:00+01:00     40
 15  2020-02-14T08:12:00+01:00     41
 16  2020-02-14T08:13:00+01:00     42
 17  2020-02-14T08:17:00+01:00     43
 18  2020-02-14T08:18:00+01:00     44
 19  2020-02-14T08:19:00+01:00     45
 20  2020-02-14T08:07:00+01:00     36
 21  2020-02-14T08:20:00+01:00     46
 22  2020-02-14T07:55:00+01:00     24
 23  2020-02-14T07:53:00+01:00     22
 24  2020-02-14T07:05:00+01:00      2
 25  2020-02-14T07:08:00+01:00      3
 26  2020-02-14T07:11:00+01:00      4
 27  2020-02-14T07:14:00+01:00      5
 28  2020-02-14T07:17:00+01:00      6
 29  2020-02-14T07:20:00+01:00      7
 30  2020-02-14T07:23:00+01:00      8
 31  2020-02-14T07:26:00+01:00      9
 32  2020-02-14T07:29:00+01:00     10
 33  2020-02-14T07:54:00+01:00     23
 34  2020-02-14T07:32:00+01:00     11
 35  2020-02-14T07:38:00+01:00     13
 36  2020-02-14T07:41:00+01:00     14
 37  2020-02-14T07:44:00+01:00     15
 38  2020-02-14T07:47:00+01:00     16
 39  2020-02-14T07:48:00+01:00     17
 40  2020-02-14T07:49:00+01:00     18
 41  2020-02-14T07:50:00+01:00     19
 42  2020-02-14T07:51:00+01:00     20
 43  2020-02-14T07:52:00+01:00     21
 44  2020-02-14T07:35:00+01:00     12
 45  2020-02-14T07:02:00+01:00      1  )

In [66]:
event.stages

,stageId,eventId,number,name,distance,status,stageType,timingPrecision,locked,code,rallyid
0,1566,125,2,Hof-Finnskog 1,21.26,Completed,SpecialStage,Tenth,True,SS2,102
1,1563,125,3,Finnskogen 1,20.68,Completed,SpecialStage,Tenth,True,SS3,102
2,1562,125,4,Nyckelvattnet 1 (Live TV Stage),18.94,Completed,SpecialStage,Tenth,True,SS4,102
3,1571,125,8,Torsby Sprint 1,2.80,Completed,SpecialStage,Tenth,True,SS8,102
4,1564,125,5,Hof-Finnskog 2,21.26,Completed,SpecialStage,Tenth,True,SS5,102
5,1565,125,6,Finnskogen 2 (Live TV Stage),20.68,Completed,SpecialStage,Tenth,True,SS6,102
6,1567,125,7,Nyckelvattnet 2,18.94,Completed,SpecialStage,Tenth,True,SS7,102
7,1568,125,16,Torsby Sprint 2,2.80,Completed,SpecialStage,Tenth,True,SS16,102
8,1572,125,18,Likenäs 2 Wolf Power Stage,21.19,Running,PowerStage,Thousandth,False,SS18,102

In [57]:
dir(event)

['__call__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_checkItinerary',
 '_checkRallyId',
 '_checkStageId',
 '_checkStages',
 '_checkStartListId',
 '_null',
 'activerally',
 'cars',
 'classes',
 'controls',
 'db',
 'db_connect',
 'dbfy',
 'dbname',
 'dbtables',
 'dump',
 'eligibilities',
 'entrySplitPointTimes',
 'exportschema',
 'fetchCars',
 'fetchItinerary',
 'fetchOverall',
 'fetchPenalties',
 'fetchRally',
 'fetchRetirements',
 'fetchSplitTimes',
 'fetchStageTimes',
 'fetchStages',
 'fetchStagewinners',
 'fetchStartList',
 'getCars',
 'getItinerary',
 'getOverall',
 'getPenalties',
 'getRally',
 'getRetirements',
 'getSplitTimes',
 'getStageIdFromCode',
 'getStageIds',
 'getStageIdsFromCode',
 'getStageTimes',
 'getStagewinners',
 'getStartlist',
 'groups',
 'itinerary',
 'lastCompletedStage',
 'legs',
 'live',
 'name',
 'nowarn',
 'overall',
 'penalties',
 'pickle',
 'q',
 'rally',
 'rallyslurper',
 'retirements',
 'richstages',
 'sdbRallyId',
 'sections',
 'splitPointTimes',
 'splitPoints',
 'stageId',
 'stageStatus',
 'stages',
 'stagetimes',
 'stagewinners',
 'startList',
 'startListId',
 'startListItems',
 'upsert',
 'warner']